<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" PrivateAssets="all" />
    <PackageReference Include="coverlet.MTP" Version="10.1.0" PrivateAssets="all" />
    <Using Include="Xunit" />
    <ProjectReference Include="../../../Domain/Domium.Domain/Domium.Domain.csproj" />
    <ProjectReference Include="../../../Domain/Domium.Domain.Abstractions/Domium.Domain.Abstractions.csproj" />
    <ProjectReference Include="../../../Eventing/Domium.Eventing.Abstractions/Domium.Eventing.Abstractions.csproj" />
  </ItemGroup>
</Project>
